AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  get-interest-test-app

  Sample SAM Template for get-interest-test-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetInterestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-interest/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetInterest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-interest
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetInterestApi:
    Description: "API Gateway endpoint URL for Prod stage for target function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-interest/"
  GetInterestFunction:
    Description: "Get Interest Lambda Function ARN"
    Value: !GetAtt GetInterestFunction.Arn
  GetInterestFunctionIamRole:
    Description: "Implicit IAM Role created for Get Interest function"
    Value: !GetAtt GetInterestFunctionRole.Arn
